dist: trusty
language: csharp
mono: none
dotnet: 1.0.1
branches:
  only:
  - master
before_install:
- sed -i 's/<SignAssembly>true<\/SignAssembly>/<SignAssembly>false<\/SignAssembly>/' src/SimpleFixture/SimpleFixture.csproj
- sed -i 's,<AssemblyOriginatorKeyFile>..\..\tools\SimpleFixture.snk</AssemblyOriginatorKeyFile>,,' src/SimpleFixture/SimpleFixture.csproj 
install:
- dotnet restore SimpleFixture.sln
script:
- dotnet test -f netcoreapp1.0 tests/SimpleFixture.Tests/SimpleFixture.Tests.csproj
