dist: trusty
language: csharp
mono: none
dotnet: 1.0.1
branches:
  only:
  - master
install:
- dotnet restore SimpleFixture.sln
script:
- dotnet test -f netcoreapp1.0 tests/SimpleFixture.Tests/SimpleFixture.Tests.csproj
