environment:
  build_version: 2.0.3
  nuget_suffix: Nightly%APPVEYOR_BUILD_NUMBER% 
  COVERALLS_REPO_TOKEN:
    secure: y0rSDEqwr4qPrtlqBPN+nuJ7XqeO2fvwjx88kYMriIiXmS/m3cBYBWYQ99SsWeQH
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
- cmd: nuget restore SimpleFixture.sln
build:
  project: SimpleFixture.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: SimpleFixture*.nupkg
  name: SimpleFixture
os: Visual Studio 2017
