environment:
  build_version: 2.0.0   
  COVERALLS_REPO_TOKEN:
    secure: y0rSDEqwr4qPrtlqBPN+nuJ7XqeO2fvwjx88kYMriIiXmS/m3cBYBWYQ99SsWeQH
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: cd src/SimpleFixture/
 - cmd: dotnet restore
 - cmd: cd ../SimpleFixture.FakeItEasy/
 - cmd: dotnet restore
 - cmd: cd ../SimpleFixture.Moq/
 - cmd: dotnet restore
 - cmd: cd ../SimpleFixture.NSubstitute/
 - cmd: dotnet restore
 - cmd: cd ../SimpleFixture.xUnit/
 - cmd: dotnet restore
 - cmd: cd ../../tests/SimpleFixture.Tests/
 - cmd: dotnet restore
 - cmd: cd ../../
build:
  project: SimpleFixture.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: dotnet pack src/SimpleFixture/project.json -o . -c Release
- cmd: dotnet pack src/SimpleFixture.FakeItEasy/project.json -o . -c Release --version-suffix RC%APPVEYOR_BUILD_NUMBER%
- cmd: dotnet pack src/SimpleFixture.Moq/project.json -o . -c Release --version-suffix RC%APPVEYOR_BUILD_NUMBER%
- cmd: dotnet pack src/SimpleFixture.NSubstitute/project.json -o . -c Release --version-suffix RC%APPVEYOR_BUILD_NUMBER%
- cmd: dotnet pack src/SimpleFixture.xUnit/project.json -o . -c Release
test_script:
- cmd: cd tests/SimpleFixture.Tests/
- cmd: CodeCoverageAppVeyor.cmd
artifacts:
- path: SimpleFixture*.nupkg
  name: SimpleFixture
