environment:
  release_version: 1.5.1
version: $(release_version).{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(release_version)'
before_build:
- cmd: nuget restore src/SimpleFixture.sln
build:
  project: src/SimpleFixture.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal