environment:
  build_version: 2.0.3
  Version: $(build_version)-Nightly%APPVEYOR_BUILD_NUMBER% 
  COVERALLS_REPO_TOKEN:
    secure: y0rSDEqwr4qPrtlqBPN+nuJ7XqeO2fvwjx88kYMriIiXmS/m3cBYBWYQ99SsWeQH
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
- cmd: nuget restore SimpleFixture.sln
build:
  project: SimpleFixture.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- cmd: cd tests/SimpleFixture.Tests/
- cmd: CodeCoverageAppVeyor.cmd
after_build:
- cmd: dotnet pack src/SimpleFixture/SimpleFixture.csproj -o ..\..\ --include-symbols --include-source
- cmd: dotnet pack src/SimpleFixture.FakeItEasy/SimpleFixture.FakeItEasy.csproj -o ..\..\ --include-symbols --include-source
- cmd: dotnet pack src/SimpleFixture.Moq/SimpleFixture.Moq.csproj -o ..\..\ --include-symbols --include-source
- cmd: dotnet pack src/SimpleFixture.NSubstitute/SimpleFixture.NSubstitute.csproj -o ..\..\ --include-symbols --include-source
- cmd: dotnet pack src/SimpleFixture.xUnit/SimpleFixture.xUnit.csproj -o ..\..\ --include-symbols --include-source
- cmd: dotnet pack src/SimpleFixture.MSTest/SimpleFixture.MSTest.csproj -o ..\..\ --include-symbols --include-source
- cmd: dotnet pack src/SimpleFixture.NUnit/SimpleFixture.NUnit.csproj -o ..\..\ --include-symbols --include-source
artifacts:
- path: SimpleFixture*.nupkg
  name: SimpleFixture
os: Visual Studio 2017
